### ISSUE TITLE
library-endlibrary

### ISSUE THREAD

**Issue by TheLazzoro** [WarRaft/IntelliJASS#1]
It doesn't recognize the library-endlibrary keywords

![image](https://github.com/WarRaft/IntelliJASS/assets/43842641/97218292-3057-4aae-a052-6ec2ac370e9b)

**Comment by nazarpunk** [comment]
Due to lack of documentation and non-obvious behavior, VJASS syntax is not supported.

**Comment by nazarpunk** [comment]
It was decided to write VJASS support for .vj files.

**Comment by nazarpunk** [comment]
Add vjass highlight for `.vj` files in version 2.0.17.
